---
title: LEGO速 data dashboard
hero_image: images/banner.png
description: Display pollution data on physical dials and sliders with LEGO速 and the
  Build HAT
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Plan your dashboard
- title: Make a LEGO速 sliding indicator
  completion:
  - engaged
- title: Make a LEGO速 gauge
- title: Make an LED scale
- title: Access the OpenAQ API
- title: Display pollution data with your dashboard
  completion:
  - internal
  completion:
  - external