title: LEGO Data Dashboard
hero_image: images/banner.png
description: invent-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Plan your dashboard
  - title: Access your chosen API
  - title: Make a LEGO sliding indicator
  - title: Make LEGO dials
  - title: Make an LED scale
  - title: Set the time with a LEGO clock
  - title: Displaying online data with your dashboard
  - title: What next?
