title: invent-project-template
hero_image: images/banner.png
description: invent-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Build a simple dashboard
  - title: Make a LEGO slider
  - title: Make LEGO dials
  - title: Make an LED scale
  - title: Set the time with a LEGO clock
  - title: Displaying online data with your dashboard
  - title: What next?
